apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-k8s-test
spec:
  selector:
    matchLabels:
      app: green-k8s-test
  replicas: 1
  template:
    metadata:
      labels:
        app: green-k8s-test
    spec:
      schedulerName: green-k8s-scheduler
      containers:
      - name: green-k8s-test
        image: timokraus/green-k8s-test:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"


