apiVersion: v1
kind: ServiceAccount
metadata:
  name: green-k8s-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: green-k8s-scheduler-cluster-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: green-k8s-scheduler
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: green-k8s-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: green-k8s-scheduler
    algorithmSource:
      policy:
        configMap:
          namespace: kube-system
          name: green-k8s-scheduler-policy
    leaderElection:
      leaderElect: true
      lockObjectName: green-k8s-scheduler
      lockObjectNamespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: green-k8s-scheduler-policy
  namespace: kube-system
data:
 policy.cfg : |
  {
    "kind" : "Policy",
    "apiVersion" : "v1",
    "predicates" : [
      {"name" : "PodFitsHostPorts"},
      {"name" : "PodFitsResources"},
      {"name" : "NoDiskConflict"},
      {"name" : "MatchNodeSelector"},
      {"name" : "HostName"}
    ],
    "priorities" : [
      {"name" : "LeastRequestedPriority", "weight" : 1},
      {"name" : "BalancedResourceAllocation", "weight" : 1},
      {"name" : "ServiceSpreadingPriority", "weight" : 1},
      {"name" : "ImageLocalityPriority", "weight" : 1},
      {"name" : "EqualPriority", "weight" : 1}
    ],
    "extenders" : [{
      "urlPrefix": "http://localhost:80",
      "prioritizeVerb": "prioritize",
      "weight": 1,
      "enableHttps": false,
      "nodeCacheCapable": false
    }],
    "hardPodAffinitySymmetricWeight" : 10
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-k8s-scheduler
  namespace: kube-system
  labels:
    app: green-k8s-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-k8s-scheduler
  template:
    metadata:
      labels:
        app: green-k8s-scheduler
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: ''
        effect: NoSchedule
      serviceAccountName: green-k8s-scheduler
      volumes:
      - name: green-k8s-scheduler-config
        configMap:
          name: green-k8s-scheduler-config
      containers:
      - name: green-k8s-scheduler-ctr
        image: gcr.io/google_containers/hyperkube:v1.16.3
        imagePullPolicy: IfNotPresent
        args:
        - kube-scheduler
        - --config=/green-k8s-scheduler/config.yaml
        - -v=10
        volumeMounts:
        - name: green-k8s-scheduler-config
          mountPath: /green-k8s-scheduler
      - name: green-k8s-scheduler-extender-ctr
        image: timokraus/green-k8s-scheduler
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /version
            port: 80
        readinessProbe:
          httpGet:
            path: /version
            port: 80
        ports:
          - containerPort: 80
        env:
        - name: MODE
          # allows the user to adjust the scheduler to the runtime of the apps to be scheduled
          value: "M" # xs, s, m, l, xl - default is xs
